### ISSUE TITLE
No connection with EBI ENA

### ISSUE THREAD

**Issue by GaloGS** [phe-bioinformatics/ena_submission#2]
Hello!
I've been using this tool for submitting sequencing runs to the ENA and it is very useful. Last time I used successfully was on December 2019.
However I'm trying to use it since some days ago and seems that it is not working anymore. It looks to me that FTP connections cannot be established with the ENA. I tried to connect manually `ftp webin.ebi.ac.uk` and I cannot connect. 

I was wondering if ENA maybe has restricted FTP connections and, in that case, if there is an easy way of modifying the code to make it work.

Thank you very much,
Galo

The error I am getting is the following:
```
You would like me to upload your files, generate all the xml files needed to submit your data to ENA, and upload the xml files to ENA.
Let me check if you have provided all the necessary information....

Checking if ftp_user_name is provided...Yes
Checking if ftp_password is provided...Yes
Checking if dir_of_input_data is provided...Yes
Checking if center_name is provided...Yes
Checking if refname is provided...Yes
Checking if data_file is provided...Yes
Checking if title_and_abstract_file is provided...Yes
Checking if out_dir is provided...Yes
Checking if data_file header order is correct....Yes
Checking if title and abstract file is in the correct format....Yes
creating checksums.....
created checksums file.  It's located in /data2/PilotoHCUV/ENA_Submission_noHuman/MTB_checksums.md5

connecting to ftp.webin.ebi.ac.uk....
Traceback (most recent call last):
  File "/data/Software/ena_submission/ena_submission.py", line 379, in <module>
    main(opts)
  File "/data/Software/ena_submission/ena_submission.py", line 267, in main
    populate_data_to_ENA.upload_data_to_ena_ftp_server(opts.dir_of_input_data,opts.refname,opts.ftp_user_name,opts.ftp_password,opts.filetype)
  File "/data/Software/ena_submission/modules/populate_data_to_ENA.py", line 181, in upload_data_to_ena_ftp_server
    print(ftp.lastErrorText())
UnboundLocalError: local variable 'ftp' referenced before assignment
```

**Comment by ulfschaefer** [comment]
Hello!
The line of code that makes the connection is

https://github.com/phe-bioinformatics/ena_submission/blob/a4138a07ebf0c3312861ac9fc34cf8f16563c5b1/modules/populate_data_to_ENA.py#L179

I am not aware they changed the address. You can try whether your username and password work on https://www.ebi.ac.uk/ena/submit/sra/ If they do it's probably a temporary problem on their side.

**Comment by GaloGS** [comment]
Thank yoy very much.

Sure, I checked that user and pass were working. 

I'll wait to see if it is fixed.

Best,
Galo
